version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - sudo apt-get update
      - sudo apt-get install -y python3 python3-pip wget openjdk-8-jdk curl
      - python3 -m pip install --upgrade pip
      - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - python3 -m pip install awscli
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.0.2311-linux.zip
      - unzip ./sonar-scanner-cli-4.6.0.2311-linux.zip
      - mv sonar-scanner-4.6.0.2311-linux  sonar-scanner
      - export PATH=$PATH:./sonar-scanner/bin
  build:
    commands:
      - sonar-scanner -Xmx4g -Dsonar.login=3d0e90ac334a4f8c42d0490d9bd6baebc6febd3c -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=priyankajoseph8_EmployeeManagement -Dsonar.organization=priyankajoseph8 -Dsonar.c.file.suffixes=- -Dsonar.cpp.file.suffixes=- -Dsonar.objc.file.suffixes=-
      - sleep 4
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=priyankajoseph8_EmployeeManagement >result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
